# Generated by Django 4.2.7 on 2023-11-30 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_app', '0002_login'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='login',
            options={'ordering': ['email']},
        ),
        migrations.AlterModelTable(
            name='login',
            table='Login',
        ),
    ]
